// shared/constants/projects.data.ts
import { Project } from '../models/project';

export const PROJECTS_DATA: Project[] = [
  {
    id: 3,
    order: 1,
    slug: 'liko-auto',
    title: 'Marketplace automobile connectée & services auto au Cameroun',
    clientName: 'Liko Auto',
    image: '/images/projects/liko-auto.png',
    isSpotlighted: true,
    keyResults: [
      { value: '200+', label: 'ventes visées / mois' },
      { icon: 'faComments', label: 'Messagerie instantanée' },
      { icon: 'faShieldAlt', label: 'Transactions sécurisées' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Contexte & Marché' },
      { id: 'challenges', label: 'Les Défis' },
      { id: 'approach', label: 'Notre Approche' },
      { id: 'solution', label: 'La Solution' },
      { id: 'process', label: 'Le Processus' },
      { id: 'result-impact', label: 'Objectifs & Impact' },
      { id: 'conclusion', label: 'Conclusion' },
    ],
    seoTitle: 'Liko Auto | Marketplace Automobile Cameroun — Achat, Vente & Services Auto',
    seoDescription:
      'Liko Auto est la première marketplace automobile connectée du Cameroun : achat et vente de véhicules, messagerie instantanée, garages partenaires, pièces détachées et accompagnement aux démarches administratives.',
    keywords:
      'marketplace automobile Cameroun, acheter voiture Cameroun, vendre voiture Douala Yaoundé, Liko Auto, garage Cameroun, pièces détachées auto Afrique',
  },
  {
    id: 11,
    order: 2,
    slug: 'association-mahol-diaspora',
    title: 'Solidarité diaspora digitale',
    clientName: 'Mahol Diaspora',
    image: '/images/projects/mahol-diaspora.png',
    isSpotlighted: true,
    keyResults: [
      { value: '+288', label: 'adhérents actifs' },
      { icon: 'faHandHoldingHeart', label: 'Collectes automatisées' },
      { icon: 'faCogs', label: 'Dashboard dédié' },
    ],
    sections: [
      { id: 'presentation', label: 'Aperçu' },
      { id: 'contexte', label: 'Contexte' },
      { id: 'defis', label: 'Défis' },
      { id: 'solution', label: 'Solution' },
      { id: 'resultats', label: 'Résultats' },
    ],
    seoTitle: 'Mahol Diaspora | Plateforme Solidaire & Engagement Communautaire',
    seoDescription: 'Portail web moderne pour l’association Mahol Diaspora : gestion de membres et collectes.',
    keywords: 'association solidaire, diaspora camerounaise',
  },
  {
    id: 1,
    order: 3,
    slug: 'for-you-media-africa',
    title: 'Plateforme média digitale panafricaine moderne',
    clientName: 'For You Média Africa',
    image: '/images/projects/for-you-media.png',
    isSpotlighted: true,
    keyResults: [
      { icon: 'faRocket', label: 'Temps de chargement < 2s' },
      { icon: 'faMobileAlt', label: '100% mobile-first' },
      { icon: 'faChartLine', label: 'SEO optimisé' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Le Client & Contexte' },
      { id: 'challenges', label: 'Les Défis' },
      { id: 'approach', label: 'Notre Approche' },
      { id: 'solution', label: 'Notre Solution' },
      { id: 'process', label: 'Le Processus' },
      { id: 'result-impact', label: 'Résultats et Impact' },
      { id: 'testimony', label: 'Témoignage' },
      { id: 'lessons-learned', label: 'Leçons apprises' },
      { id: 'conclusion', label: 'Conclusion et CTA' },
    ],
    seoTitle: 'For You Média | Plateforme d’Information et Divertissement Africaine',
    seoDescription: 'Développement d’une interface web dynamique et interactive pour For You Média Africa.',
    keywords: 'média africain, actualité Afrique, For You Média',
  },
  {
    id: 4,
    order: 4,
    slug: 'soprano-vesinet',
    title: 'Expérience digitale immersive pour un restaurant gastronomique',
    clientName: 'Soprano Vésinet',
    image: '/images/projects/soprano-vesinet.png',
    isSpotlighted: true,
    keyResults: [
      { icon: 'faUtensils', label: 'Menu interactif' },
      { icon: 'faMagic', label: 'Animations premium' },
      { icon: 'faCalendarCheck', label: 'Réservation fluide' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Le Client & Contexte' },
      { id: 'challenges', label: 'Les Défis' },
      { id: 'approach', label: 'Notre Approche' },
      { id: 'solution', label: 'Notre Solution' },
      { id: 'process', label: 'Le Processus' },
      { id: 'result-impact', label: 'Résultats et Impact' },
      { id: 'lessons-learned', label: 'Leçons apprises' },
      { id: 'conclusion', label: 'Conclusion et CTA' },
    ],
    seoTitle: 'Soprano Vésinet | Restaurant Italien Haut de Gamme',
    seoDescription: 'Conception d’un site vitrine élégant pour le restaurant Soprano au Vésinet.',
    keywords: 'restaurant italien Le Vésinet, Soprano Vésinet',
  },
  {
    id: 5,
    order: 5,
    slug: 'amore-mio',
    title: 'Plateforme e-commerce & expérience de marque haut de gamme',
    clientName: 'Amore Mio',
    image: '/images/projects/amore-mio.png',
    isSpotlighted: true,
    keyResults: [
      { icon: 'faHeart', label: 'Taux de conversion +35%' },
      { icon: 'faMobileAlt', label: 'UX Ultra-fluide' },
      { icon: 'faRocket', label: 'Temps de réponse < 1.5s' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Contexte & Marque' },
      { id: 'challenges', label: 'Les Défis' },
      { id: 'solution', label: 'Notre Solution' },
      { id: 'result-impact', label: 'Résultats & Impact' },
      { id: 'conclusion', label: 'Conclusion' },
    ],
    seoTitle: 'Amore Mio | Expérience Digital & E-commerce Premium',
    seoDescription: 'Conception et développement d’une plateforme web élégante et performante pour la marque Amore Mio.',
    keywords: 'Amore Mio, e-commerce luxe, expérience digitale, Évolia Tech',
  },
  {
    id: 2,
    order: 6,
    slug: 'stella',
    title: 'Boutique e-commerce headless premium',
    clientName: 'Stella',
    image: '/images/projects/stella.png',
    isSpotlighted: true,
    keyResults: [
      { icon: 'faShoppingCart', label: 'Checkout ultra-rapide' },
      { icon: 'faServer', label: 'Architecture Headless' },
      { icon: 'faShieldAlt', label: 'Paiements sécurisés' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Le Client & Contexte' },
      { id: 'challenges', label: 'Les Défis' },
      { id: 'approach', label: 'Notre Approche' },
      { id: 'solution', label: 'Notre Solution' },
      { id: 'process', label: 'Le Processus' },
      { id: 'result-impact', label: 'Résultats et Impact' },
      { id: 'testimony', label: 'Témoignage' },
      { id: 'lessons-learned', label: 'Leçons apprises' },
      { id: 'conclusion', label: 'Conclusion et CTA' },
    ],
    seoTitle: 'Développement E-commerce Stella | Expert Vendure & Angular',
    seoDescription: 'Découvrez l’architecture headless Vendure et le frontend Angular ultra-rapide.',
    keywords: 'e-commerce Afrique, Vendure, NestJS',
  },
  {
    id: 6,
    order: 7,
    slug: 'celebrate-congo',
    title: 'Portail culturel & événementiel panafricain d’envergure',
    clientName: 'Celebrate Congo',
    image: '/images/projects/celebrate-congo.png',
    isSpotlighted: true,
    keyResults: [
      { value: '50k+', label: 'visiteurs uniques' },
      { icon: 'faTicketAlt', label: 'Billetterie en ligne' },
      { icon: 'faGlobeAmericas', label: 'Diffusion internationale' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'client-context', label: 'Contexte & Vision' },
      { id: 'challenges', label: 'Les Défis Techniques' },
      { id: 'solution', label: 'La Plateforme' },
      { id: 'result-impact', label: 'Impact Culturel' },
      { id: 'conclusion', label: 'Conclusion' },
    ],
    seoTitle: 'Celebrate Congo | Portail Culturel & Billetterie Événementielle',
    seoDescription: 'Développement du portail événementiel et culturel Celebrate Congo avec billetterie intégrée.',
    keywords: 'Celebrate Congo, événementiel Congo, billetterie Afrique, Évolia Tech',
  },
  {
    id: 7,
    order: 8,
    slug: 'presidentielles-cameroun',
    title: 'Dispositif numérique d’engagement citoyen & données électorales',
    clientName: 'Présidentielles Cameroun',
    image: '/images/projects/presidentielles-cameroun.png',
    isSpotlighted: true,
    keyResults: [
      { value: '100k+', label: 'Engagements citoyens' },
      { icon: 'faUsers', label: 'Cartographie interactive' },
      { icon: 'faMobileAlt', label: '100% Responsive' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'contexte', label: 'Contexte Citoyen' },
      { id: 'defis', label: 'Défis de Mobilisation' },
      { id: 'solution', label: 'Dispositif Numérique' },
      { id: 'resultats', label: 'Impact & Engagement' },
    ],
    seoTitle: 'Présidentielles Cameroun | Dispositif d’Engagement Citoyen',
    seoDescription: 'Plateforme interactive et cartographie dynamique d’engagement pour les présidentielles au Cameroun.',
    keywords: 'Présidentielles Cameroun, engagement citoyen, cartographie électorale, Évolia Tech',
  },
  {
    id: 8,
    order: 9,
    slug: 'presidentielles-senegal',
    title: 'Plateforme d’information & suivi en temps réel des élections',
    clientName: 'Présidentielles Sénégal',
    image: '/images/projects/presidentielles-senegal.png',
    isSpotlighted: false,
    keyResults: [
      { value: '99.99%', label: 'Disponibilité serveur' },
      { icon: 'faChartLine', label: 'Data visualization live' },
      { icon: 'faShieldAlt', label: 'Haute sécurité & anti-DDoS' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'contexte', label: 'Contexte Électoral' },
      { id: 'defis', label: 'Défis de Scalabilité' },
      { id: 'solution', label: 'Architecture & Dashboard' },
      { id: 'resultats', label: 'Résultats & Sécurité' },
    ],
    seoTitle: 'Présidentielles Sénégal | Suivi Électoral & Visualisation de Données',
    seoDescription: 'Plateforme hautement sécurisée de suivi des résultats et actualités des élections présidentielles au Sénégal.',
    keywords: 'Présidentielles Sénégal, données électorales, haute disponibilité, Évolia Tech',
  },
  {
    id: 9,
    order: 10,
    slug: 'parti-politique-purs',
    title: 'Portail institutionnel & espace adhérents pour le P.U.R.S',
    clientName: 'Parti Politique P.U.R.S',
    image: '/images/projects/purs.png',
    isSpotlighted: false,
    keyResults: [
      { value: '+10k', label: 'Adhérents enregistrés' },
      { icon: 'faUserCheck', label: 'Gestion des membres' },
      { icon: 'faNewspaper', label: 'Espace média & actu' },
    ],
    sections: [
      { id: 'overview', label: 'Aperçu' },
      { id: 'contexte', label: 'Vision & Engagement' },
      { id: 'defis', label: 'Gestion des Adhésions' },
      { id: 'solution', label: 'Portail & Espace Membre' },
      { id: 'resultats', label: 'Impact Communautaire' },
    ],
    seoTitle: 'Parti Politique P.U.R.S | Portail Institutionnel & Adhésions',
    seoDescription: 'Conception du portail officiel et de l’espace adhérents sécurisé du parti politique P.U.R.S.',
    keywords: 'P.U.R.S, parti politique, portail membre, Évolia Tech',
  },
  {
    id: 10,
    order: 11,
    slug: 'elites-voyages',
    title: 'Voyage de luxe sur-mesure',
    clientName: 'Elites Voyages',
    image: '/images/projects/elites-voyages.png',
    isSpotlighted: false,
    keyResults: [
      { icon: 'faGlobeAmericas', label: 'Destinations infinies' },
      { icon: 'faCameraRetro', label: 'Galeries immersives' },
      { icon: 'faMapMarkedAlt', label: 'Cartographie interactive' },
    ],
    sections: [
      { id: 'concept', label: 'La Vision' },
      { id: 'destinations', label: 'Destinations' },
      { id: 'interface', label: 'Interface' },
    ],
    seoTitle: 'Elites Voyages | Agence de Voyage sur-mesure & Séjours de Luxe',
    seoDescription: 'Plateforme digitale conçue pour l’exploration de destinations mondiales.',
    keywords: 'voyage sur mesure, agence de voyage luxe',
  },
];